$(function() {
	$('.main').hide();
	$('#block1').show();
	$('#tab1').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block1').show();
	});
	$('#tab2').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block2').show();
	});
	$('#tab3').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block3').show();
	});
	$('#tab4').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block4').show();
	});
	$('#tab5').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block5').show();
	});
	$('#tab6').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block6').show();
	});
	$('#tab7').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block7').show();
	});
	$('#tab8').click(function(){ 
		$('.nav-link').removeClass('active');
		$(this).addClass('active');
		$('.main').hide();
		$('#block8').show();
	});
});